// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx ts-node prisma/seed.ts',
  },
  datasource: {
    url: process.env["DIRECT_URL"]!,         // direct postgres URL for migrations/push
    accelerateUrl: process.env["DATABASE_URL"], // prisma:// accelerate URL for queries
  },
});
